[package]
name = "kboot"
version = "0.1.0"
edition = "2018"
authors = ["Kees van Voorthuizen <me@keesvv.nl>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
uefi = "0.11.0"
log = "0.4.14"
rlibc = "1.0.0"
